Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
dftest = read_invent_ODS("2022", fgas1[0])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mIndexError[0m                                Traceback (most recent call last)
Input [0;32mIn [5][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m dftest [38;5;241m=[39m [43mread_invent_ODS[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43m2022[39;49m[38;5;124;43m"[39;49m[43m,[49m[43m [49m[43mfgas1[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[43m)[49m

File [0;32m~/Documents/dare_website_local/fig_mods/nextstep.py:41[0m, in [0;36mread_invent_ODS[0;34m(year, species)[0m
[1;32m     37[0m [38;5;28;01mimport[39;00m [38;5;21;01mglob[39;00m
[1;32m     39[0m csv [38;5;241m=[39m glob[38;5;241m.[39mglob([38;5;124mf[39m[38;5;124m"[39m[38;5;124mdata/UK_NIR_[39m[38;5;132;01m{[39;00myear[38;5;132;01m}[39;00m[38;5;124m_[39m[38;5;132;01m{[39;00mspecies[38;5;132;01m}[39;00m[38;5;124m.csv[39m[38;5;124m"[39m)  
[0;32m---> 41[0m df [38;5;241m=[39m pd[38;5;241m.[39mread_csv([43mcsv[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m, index_col[38;5;241m=[39m[38;5;124m"[39m[38;5;124mGREENHOUSE GAS SOURCE AND SINK CATEGORIES[39m[38;5;124m"[39m)
[1;32m     43[0m ODS [38;5;241m=[39m df[38;5;241m.[39mloc[[38;5;124m"[39m[38;5;124mF.  Product uses as substitutes for ODS(2)[39m[38;5;124m"[39m]    
[1;32m     45[0m dfODS [38;5;241m=[39m pd[38;5;241m.[39mDataFrame(ODS)

[0;31mIndexError[0m: list index out of range
IndexError: list index out of range

